apiVersion: v1
kind: Secret
metadata:
  name: ftps.tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPRENDQWlBQ0NRQ0NNRHpaSHc5ZkZ6QU5CZ2txaGtpRzl3MEJBUXNGQURCZU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQnd3RlVHRnlhWE14Q3pBSkJnTlZCQW9NQWpReU1RMHdDd1lEVlFRRERBUm1kSEJ6TVNNdwpJUVlKS29aSWh2Y05BUWtCRmhSdWMybHRiMjVBYzNSMVpHVnVkQzQwTWk1bWNqQWVGdzB5TURBNU1qTXhOREkzCk1qZGFGdzB5TVRBNU1qTXhOREkzTWpkYU1GNHhDekFKQmdOVkJBWVRBa1pTTVE0d0RBWURWUVFIREFWUVlYSnAKY3pFTE1Ba0dBMVVFQ2d3Q05ESXhEVEFMQmdOVkJBTU1CR1owY0hNeEl6QWhCZ2txaGtpRzl3MEJDUUVXRkc1egphVzF2YmtCemRIVmtaVzUwTGpReUxtWnlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUF4eFN3SXRnWGNaOFpzOVVsVTJjZllQLzc0Mk9aRkFuNXVHSFROWkdoOXpQUWdYTDJHRi8wZnBCK0t5VS8KUEhSNmxPQWVraTFMUVhib3FVUXBxZGlUVnYyVEtzblRGZFJua3prRG45K1MyZytGWjZRUXRFTmFaT2lMY0ErdwpFYVYzREJ3bVE2V2hpTksxblZlME5adzVmQWtjVXdSYUZ3TldyVFRheGgzQ2pScXFvYlpjT0VWdTVDMTdKeEs0ClZEcmhIdUlSclA4bzhBc3FRb0svTUZWQ0djaTlWVnJSVXRHdzRLWEJadVlNYW5FZGFOTG80K2JYZEdlZTJpeXMKNFdsSGtJRU9wMHF4MjdnRS9oZ1dWNTZnRU0zUi90bEF1Qy8xYUUzaFVKWStzU092a1BhQ3U3MEI2WmhRNHN0TQpIcVo1Mm1BWkNzc3lCNGNnVCttUDY4U2pQd0lEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ05Ma0t6CitzTVZBeGszcXpIU2JOdUpEcVJ3RVFDUENvVDZ2dGkrM0RubDVNenJDQzNJalI4VW96Y0FyVVU0Wmh3cFJJTVYKVXpPclB3MGpMT1E4Vkk5bWk3ejEyRlFCZjlVWDA0STZjYlRWMTU1MitHNmdyaFRGVTR5UWtmT0hvaTZrWm1tQwpIWnNWVnUyVjltSE95OXNNSXZnVEZ4WnlSa3NMQVplK3NaVmtxLzFXNXZBbnZMc0JYcWw4aUhkdUxzbHBLSFNlCnRvRFM2K21HT3Jld2JLRG1FU2VmV3Q3eVFQaGQ5TnJNaThWUDFOTDF3OVFwelpid1QwVnZWRXFyU2hiYXU1QisKWVVTOHlPUHVQVXBVNjdsSXZrRHFvZTRLc0JwQWlXYUI3ZGxocVF4bkRCcm1ValBJL3FkZGg4eUFuMFVadlhNegpSazhZMDFWa20wdGR1YVE4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRREhGTEFpMkJkeG54bXoKMVNWVFp4OWcvL3ZqWTVrVUNmbTRZZE0xa2FIM005Q0JjdllZWC9SK2tINHJKVDg4ZEhxVTRCNlNMVXRCZHVpcApSQ21wMkpOVy9aTXF5ZE1WMUdlVE9RT2YzNUxhRDRWbnBCQzBRMXBrNkl0d0Q3QVJwWGNNSENaRHBhR0kwcldkClY3UTFuRGw4Q1J4VEJGb1hBMWF0Tk5yR0hjS05HcXFodGx3NFJXN2tMWHNuRXJoVU91RWU0aEdzL3lqd0N5cEMKZ3I4d1ZVSVp5TDFWV3RGUzBiRGdwY0ZtNWd4cWNSMW8wdWpqNXRkMFo1N2FMS3poYVVlUWdRNm5TckhidUFUKwpHQlpYbnFBUXpkSCsyVUM0TC9Wb1RlRlFsajZ4STYrUTlvSzd2UUhwbUZEaXkwd2Vwbm5hWUJrS3l6SUhoeUJQCjZZL3J4S00vQWdNQkFBRUNnZ0VCQUlqTWxJUTlEVThNVHZNZUlqbi9nTFo4OEsrK1B2QmdNbk1hOWJHMzB4NDEKUXEvUk9YNWlZWFdmQUxQUk1uVHViVlZqOUYzcU5lNVVNV2d1NkpwSHNtZHljL0JSSTNXNnNUbWZVZmhILzNkTQpkeFZTemcrd3dLcmFpUWFHSVN6ZkVNRUhqdHVwTXlqNzhjU2ZBYnhkRDd0RjMyckVjTXVqaGFvYnljR2RyWlNiCmFoQ2tUcExrNjV0ckorZ3hpbXh2b0JNdFlUYy9ielJTUDFZVWNvbEVQVjBSZ3VSRzF1QjIzSzVudm9ITnk1NzYKRGpRaDlpRmJlZ1hHOVIzdDJHeGdNOTFENGgvbFQ0Z1JTTTEzUGNrcU5GWmNRYURGS00zS2dLa2xGcFRhcHUxdApSV0lPRGFKWnNsMVJkNkordEdrSFZXcms0alB1RlNYUWRROXl5ckhTQkRFQ2dZRUE1eUVCUG5JckVtSm1qU0VsCkVlaWQvcVJGalVqcDlyY2N0bUM3VnZ4d1dqZDRmVk1IT2ZSdkJjUWhONm8reThUWWNLellLTUd3eTZGMngzSzYKOWNpaFd6aUpxMEJsaWRrR09lWERBT0JMcStnSDRuRDc4aVA2WC9NcE96ZlVYTDNEN3lrS2hmTWhNYnlqeWdJagpMblN3VklHNDlnRTVWcFRSSU1JbFNHdU9tdnNDZ1lFQTNJRFhnRTNEVTg2OS9HNStidVMwclcvbm04QkZsNTA3CnlhN3Y2WFhzQjl1dUpmeDVFYVgwdU1ydUZacHVLODJCQ3Zqd3JRbUt6cGdDT3krMzVTekRzVWloZVl6azZOQVEKR0lhOUFLS3N3QnVnaFJOczIxTDNLaGJIdzV5SDFUR3FLSWRmU0wwbS9aKzBrZHhFS2dqOGxBdjZOSTE4SFBzTgpid2Q1aHEwSkpZMENnWUVBMjRCY3poRmZGbmFkTGlyc0tiWGhWcFJyK1dIbDBJaldtOTRDRFBweE9UeTFFVkJvCjdJRlhid0oxQ1lpRldyLzNUZ3JZdnR3MEt5K012cDRYTUpUNXFNaG85bHFTRS9nb0VaUkRQZkhGNjl6UW9CenQKS1dsQnZ4NFBhazM3UUpoNEhBbStGTGh5TGVvWkl5QWtpVm9JbkRrV2o0dGFDUUFNSERCRmVDR3RyVUVDZ1lBWApZeGI0UmNjczBXVzNLMlQva0FSVnpPT3MwbFRQUXQ3L2dpMXgvbzdkT29DYkNNOHlmdjZZeHZVL2wxU09Fc3JZCkJoVkkxUlZDMmo2S1ZvSlRyVTdJTStMa2lId1M4Vlp6czM3Q1hYNmpGWXNOOGtSK2NxdENiSTRkZ2pHcC9BMkgKSk95SFE0Q3FMOUV3RTBPcmphNTBhVnpOVENCWTFvdlROZUMrMXdWOFZRS0JnRDhaMCt1YzN0Y05NUXhPTUtragplbDVPSmIwRWl4VTAxQkN4ZWJucGUrdFVPMmxoUElWUmh1VHRSbmJkaXgzKzNPSytCK0lLSU5nNGxyZk5aVGFFCkZEYTVYN1FkOHB6bG9xakFNVFZ6djdaOE53eXFFVndUN3ppT2tVTU9mbG9kbkc5ZGRtNDA0c2sxaEtsNzlQNEMKRTAyTEtDOHdzVGY3cjdieXNIbGtLSGdkCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:42
        ports:
        - containerPort: 20
          name: ftp-connection
          protocol: TCP
        - containerPort: 21
          name: ftp-data
          protocol: TCP
        - containerPort: 20000
          name: pftp-data-0
          protocol: TCP
        - containerPort: 20001
          name: pftp-data-1
          protocol: TCP
        env:
        - name: USERNAME
          value: "nsimon"
        - name: PASSWORD
          value: "nsimon"
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
          - name: config
            mountPath: /etc/vsftpd/config
            readOnly: true
          - name: tls
            mountPath: /etc/ssl/certs
      volumes:
        - name: config
          configMap:
              name: ftps-config
        - name: tls
          secret:
            secretName: ftps.tls
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 21
    name: ftp-connection
    targetPort: 21
  - port: 20
    name: ftp-data
    targetPort: 20
  - port: 20000
    name: pftp-data-0
    targetPort: 20000
  - port: 20001
    name: pftp-data-1
    targetPort: 20001
