apiVersion: v1
kind: Secret
metadata:
  name: nginx.tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPakNDQWlJQ0NRQzJ5b0VUY1hJV2VUQU5CZ2txaGtpRzl3MEJBUXNGQURCZk1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQnd3RlVHRnlhWE14Q3pBSkJnTlZCQW9NQWpReU1RNHdEQVlEVlFRRERBVnVaMmx1ZURFagpNQ0VHQ1NxR1NJYjNEUUVKQVJZVWJuTnBiVzl1UUhOMGRXUmxiblF1TkRJdVpuSXdIaGNOTWpBd09USXpNVFV4Ck5USXpXaGNOTWpFd09USXpNVFV4TlRJeldqQmZNUXN3Q1FZRFZRUUdFd0pHVWpFT01Bd0dBMVVFQnd3RlVHRnkKYVhNeEN6QUpCZ05WQkFvTUFqUXlNUTR3REFZRFZRUUREQVZ1WjJsdWVERWpNQ0VHQ1NxR1NJYjNEUUVKQVJZVQpibk5wYlc5dVFITjBkV1JsYm5RdU5ESXVabkl3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNkZ2ZOUnE4dk42Q25GR2l5NWVhQlowUGhqNGRWUWNIMWU4V0VKbG8rVGp3WjI2a09UcXg0TktmQTIKZjRha3BDQVlFRmY0ZUJwQU9zbDhGMDhGbmR4SXFhSTJxQUMwVEZwenBOVEg0VzNsZEljejJQNXZXQmVqbkg0SQo4M1BqckJwR0p0ZU1LVzB1MjFIdTNscS9TUmpONVBNR1E3Y25WVWgrbmxJeVRtVmxMVU83Z0hDN0w3QUlBVHppCmRnUGplTy9FUGwzNXUrbWc5VWo0M1YvSGxSOXhtSm1jWmg1L3QwTXIxdWFDMHUvRWducGVmWmUyOWtpT1BIODQKS1lCVkg0U2UrUld2K1ZCcDhlWXk1TXlob3NFekFiVWhtRjV5RHV4Nms1YmFxMnF6dkhGQi80UFF6TFpLa3dJMQpkLzUrMXA5bTJhbGxCeHlVekl4NmJqUFJvaWVUQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRzF0CndmdGYyWWU0TEZwNjU0R2YrSUsvdUQvaGVVb1Uweksza2hSWTRUc3VwUDJUQng0UFhLVVlzcDhMWWZBU0pxTVIKNXdVSnhvSzU1UUVGMktJc2FmdlFhTlcyanU1QmpZY3pwM2Naa28raGxBT0FRd0FwMlVvUFd5RVk4dVZCZTVsawphbVpxSzRGTnN5VU5kc1ZjZlA2ajhhZVVyL3NvKy9TWmJhd1lwZ0s0UnYwc3d1ZDVuNEw4azFKMXBjSjF2dzdmCkJjdTlpSjR5emFvZURRZHNIN2kzb2g3NjBGUE1UcWk3TG4xZklISjNPdjdFL3ZMaEszaTZlSDdNTkRibk1xeE4KNzJFTXVlNHBpYWdiNnNya1dZMEtNS2VZN0VrUWdYUG9seS9WNHF0YW03TTl0T015TGdodVpYdGZwc3Y0TWVOZwplcU01cnhsT2grTWphWERFM0QwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ2RnZk5ScTh2TjZDbkYKR2l5NWVhQlowUGhqNGRWUWNIMWU4V0VKbG8rVGp3WjI2a09UcXg0TktmQTJmNGFrcENBWUVGZjRlQnBBT3NsOApGMDhGbmR4SXFhSTJxQUMwVEZwenBOVEg0VzNsZEljejJQNXZXQmVqbkg0STgzUGpyQnBHSnRlTUtXMHUyMUh1CjNscS9TUmpONVBNR1E3Y25WVWgrbmxJeVRtVmxMVU83Z0hDN0w3QUlBVHppZGdQamVPL0VQbDM1dSttZzlVajQKM1YvSGxSOXhtSm1jWmg1L3QwTXIxdWFDMHUvRWducGVmWmUyOWtpT1BIODRLWUJWSDRTZStSV3YrVkJwOGVZeQo1TXlob3NFekFiVWhtRjV5RHV4Nms1YmFxMnF6dkhGQi80UFF6TFpLa3dJMWQvNSsxcDltMmFsbEJ4eVV6SXg2CmJqUFJvaWVUQWdNQkFBRUNnZ0VBSmZKQjJhSkhCb054Vk1BYW1GQzZGZ2xuWGtEeE1HRDVnMThwM3JKOFFyT0oKZmlxd1B5cFJvaUJCZEEvRE0zVXJHa0VOd0puRzBVU1llQ0h4Y3N2Mlh6Y25FbjNsTllyVG05clJQSnFON0dMbgprOUVxYzA3STJ5ei9uRTV5MUI0SmNtODNMTmhxS29qQ000YzBXN05UbTM4V0lhTTh3K2dqQUFaS2pUNGY1WURpCmRubHJDcGhpZkJsZjU2SlMxTE1iNTNIRE9PUHFjREc5WnZyRHNTcWxWMEREZ09iL0xVRUhyUEU3SER6VWJJUzMKdDcwOTQ4WTZvUXJzQVg4TFFndmtidEpxZmZOcHpqRlZFaTdieS9SZDYzVys5MTRZWWlWNXdsOVlJSWJ1THJYaQpDeTBDMjE5blF4YldrdkRQY2pxZkhnTVZHUTY5TXAwejRBRHRGT0JRU1FLQmdRRExLcGwveXV0TXVjUllJV084CnZKdzdNc1VSc1FWSzR2eFNjQjFFTG1Tb2xVVmc0SlRzN3JyNmJLdXYvUDY3Y2dibU9uMkNOckFyRUo2bm9Zc04KWERQaUZKbVNRd2xlWFUzT25GdVFEZkNGbkFHSFM4YlVDenUvMTZSUDZLZGloYzk2ZUdhYlZhcW5uY3pOOVhxSgpPK0Mxb2JOTTlWb2NQWmJWa3E3Z3NGVzZud0tCZ1FER2Q3VXdWWmk3SEtBNEtHNUlxTWpSUWZ1ZEplSkRLaVh5Cld3WlZ6cC9reHBqTWozci82bUtZTWVZNDZqR0ZPVGdrUGR5dDFHT21kZXdhLzZhNDNtQkF6dWxQUGxjZU5MeEwKaTRNRzdhNG1JQ1NCM3A4aXlwdG1mV1hqcTVUOCswR2k5Z25hWW94MVZUT25JT0svWS9pSXdLZkhLMmJyeXNKYwpocTJ1eGhiaWpRS0JnSEs1eTVSdWNoRVJsZDV1ZkhQSHpqRmZxZ2tqZldtY1kvL3BiNTFnMVZhZGRHQVFjZ2laCmh0eURJVEJ3SFNpY2EyajIvb2paZVFIWWtMNzRhaDFSUTdzWEJ1R2hHVmxBTnYvRks2OWRMOFZESTFuVFlLTzgKOURDUkJTaGFxS3JxQlErVGpkMkpzcVNVWjJLbWpGdVNoSUlNbmNPSGlTc0pYSE9lTVVLUVVOamhBb0dBU1ZpYwpJWXpBc1FYWFFHblF1QkdJaGEwNDY4N0FXOG9MMUJGSHVoWnVpUUhNSG0wNEs3UFhWQis4MFhQYmNUekFQc1NOCjliLzBRK1I0cVZHcHI5Q2ZDZFJ0N05kQkl1eWlXZGpwUjNvM1RlZTdGalBMNC9PMGtwL3RNOEtKZ1NUcUVPdVUKb0p5akJBbkUyUk1TT1dFY3pJMUdkQmphSkhIK2VtdGJiS2ZRZFZFQ2dZQS9QMlkveEFNU29KYlhSRHdhcVhZYgpjSkh5NndDbm5Zc2p5WDR1V1RJU2RFREJFajFIajJpTkUvdk9CdGRRcGlTdk5rR1BRVVZ5MmZjRlhyNnZEQ252ClZ6NlFKV2w4UnM2ZGNnUStNNVlzSUpLdXZKVjhOOWJBZlJSS1hsbkdWcWRUbVIrd2RiQ256cmd6c3NhZ1E3MzEKOUlOTm94Mm9vQWdGVG9YV1NRNVgrZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:42
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
          protocol: TCP
        env:
        - name: SSH_USERNAME
          value: "nsimon"
        - name: SSH_PASSWORD
          value: "nsimon"
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d/
            readOnly: true
          - name: tls
            mountPath: /etc/nginx/ssl
      volumes:
        - name: config
          configMap:
              name: default-nginx-config
        - name: tls
          secret:
            secretName: nginx.tls
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  - port: 22
    name: ssh
    targetPort: 22
