apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: influxdb
data:
  influxdb.conf: |
    [meta]
      bind-address=":8088"
      dir = "/data/influxdb/meta"

    [data]

      series-id-set-cache-size = 100

      dir = "/data/influxdb/data"

      wal-dir = "/data/influxdb/wal"

    [coordinator]

    [retention]

    [shard-precreation]

    [monitor]

    [admin]

    [http]
      enabled = true

      bind-address = ":8086"

    [logging]

    [subscriber]

    [[graphite]]

    [[collectd]]

    [[opentsdb]]

    [continuous_queries]

    [tls]
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  labels:
    app: influxdb
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_ADMIN_USER: nsimon
  INFLUXDB_ADMIN_PASSWORD: nsimon
  INFLUXDB_USER: usernsim
  INFLUXDB_USER_PASSWORD: usernsim
